service: simple-blog-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1
  lambdahashingVersion: 20201221

functions:
  start:
    handler: handler.start
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      PORT: 3000
      DB_HOST: simpleblogdb.cwy0y6mp6fjt.us-east-1.rds.amazonaws.com
      DB_USER: root
      DB_PWD: mysqlpassword
      DB_NAME: SimpleBlogDB